name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GHCR using Personal Access Token
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/nikhilnamaji/nextjs-app:latest ./nextjs-app

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/nikhilnamaji/nextjs-app:latest